#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i 's/0/1/g' /etc/default/haproxy
front_end="frontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n"
back_end="backend web-backend\n\tbalance roundrobin\n\tserver 356-web-01 104.196.57.225:80 check\n\tserver 356-web-02 35.231.8.144:80 check"
sudo sed -i "\$a$front_end\n$back_end" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
