#!/usr/bin/env bash
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/holbertonscript.pid
trap "echo I am invincible!!!; sudo rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
i=0
while ((i >= 0))
do
    echo "To infinity and beyond"
    sleep 2
    i=$((i+1))
done
