#!/usr/bin/env bash
#displays To infinity and beyond indefinitely, displays I am invincible!!! when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
i=0
while ((i >= 0))
do
    echo "To infinity and beyond"
    sleep 2
    i=$((i+1))
done
