#!/usr/bin/env bash
# transfers a file from our client to a server
if (( "$#" < 3 ))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp "$3"@"$2" -i "$1" "$4":~/
fi
