#!/usr/bin/env bash
# Configure  Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
page="location /redirect_me {rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;}"
sudo sed -i "30i $page" /etc/nginx/sites-available/default
sudo service nginx restart
