#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
page="location /redirect_me {rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;}"
sed -i "30i $page" /etc/nginx/sites-enabled/default
sudo service nginx restart
