#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo service nginx start
chmod 700 /etc/nginx/nginx.conf
user="user nginx;"
sudo sed -i "2i $user" /etc/nginx/nginx.conf
sudo service nginx restart
